language: node_js
before_install:
  - sudo apt-get install optipng -y
  - sudo apt-get install libjpeg-progs -y
node_js:
  - 0.10
before_deploy: make build
deploy:
  provider: divshot
  skip_cleanup: true
  api_key:
    secure: VlTaXKDy5wLy9voWJn+mDI+bT34QLIgz9jwgOlLRzg45c0ru2FsiLWHib7SsGHRl6Bep8YKj3DdZEW37jm8xzIM1LjwmVI4PjXPm+E6Y//y2x7fm7X2QjRgzQb04+wiPfshqbp1Z+imnaunyDdYPt1hiVfMV4fBTqv4GK3REGq4=
  environment: development
  on:
    repo: jsdelivr/beta.jsdelivr.com
    branch: master
